version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: proxyshop_postgres
    restart: always
    environment:
      POSTGRES_USER: proxy_admin
      POSTGRES_PASSWORD: proxy_password
      POSTGRES_DB: proxyshop_db
    ports:
      - "5432:5432"
    volumes:
      - proxyshop_data:/var/lib/postgresql/data

volumes:
  proxyshop_data: